version: '3'
services:
  app:
    image: gmair_jpush
    container_name: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    